name: manage-azure-policy-01b664bb
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policyservicesaz/policies/P-Not_allowed_resource_types_5ede4604-277e-4745-ba5a-dafb2fe0eb4f/**'
#      - .github/workflows/manage-azure-policy-01b664bb.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_01b664bb}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policyservicesaz/policies/P-Not_allowed_resource_types_5ede4604-277e-4745-ba5a-dafb2fe0eb4f/**
